# Generated by Django 4.1.7 on 2023-06-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications', '0002_userchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='group_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='auth.group'),
        ),
    ]
